# Generated by Django 5.0.6 on 2025-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering', 'id']},
        ),
        migrations.AddField(
            model_name='productimage',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
